easy_admin:
    entities:
        # List the entity class name you want to manage
        Movie:
            class: App\Entity\Movie
            label: 'Films'
            form:
                fields: ['title', 'genres']
            list:
                fields: 
                    - title
                    - { property: "createdAt", label: "Date d'ajout"}
                    - updatedAt
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            form:
                fields:
                    - email
                    - { property: roles, type: 'choice', type_options: { expanded: true, multiple: true, choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' }} }
        Job:
            class: App\Entity\Job
            label: 'Postes'
            form:
                fields:
                    - name
                    - department
      #  - App\Entity\Genre
      #  - App\Entity\Person
      #  - App\Entity\Job
      #  - App\Entity\Department
      #  - App\Entity\CrewMember
      #  - App\Entity\Actor
      #  - App\Entity\Director
